"""Create the initial experiment-platform schema.

Revision ID: 0001_initial_schema
Revises: None

The ORM models document the intended tables and constraints. Generate and
review concrete operations before using this placeholder against a database.
"""

from collections.abc import Sequence


revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the initial schema after autogenerated operations are reviewed."""

    # TODO: commit reviewed op.create_table/op.create_index calls here.
    pass


def downgrade() -> None:
    """Reverse the initial schema in dependency-safe order."""

    # TODO: add explicit op.drop_* calls; never use metadata.drop_all in a migration.
    pass
